name: YKS Bot

on:
  schedule:
    - cron: '0 4 * * *'
    - cron: '50 4 * * *'
    - cron: '0 5 * * *'
    - cron: '30 16 * * *'
    - cron: '0 17 * * *'
    - cron: '30 20 * * *'

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt

      - name: 07:00
        if: github.event.schedule == '0 4 * * *'
        run: python bot.py 0700
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: 07:50
        if: github.event.schedule == '50 4 * * *'
        run: python bot.py 0750
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: 08:00
        if: github.event.schedule == '0 5 * * *'
        run: python bot.py 0800
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: 19:30
        if: github.event.schedule == '30 16 * * *'
        run: python bot.py 1930
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: 20:00
        if: github.event.schedule == '0 17 * * *'
        run: python bot.py 2000
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: 23:30
        if: github.event.schedule == '30 20 * * *'
        run: python bot.py 2330
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
